  sessionInfo(                        )
# if ( !require( MASS                 )  ) install.packages( "MASS"                        , repos = "http://cran.rstudio.com" )
# if ( !require( devtools             )  ) install.packages( "devtools"                    , repos = "http://cran.rstudio.com" )
# if ( !require( ranger               )  ) install.packages( "ranger"                      , repos = "http://cran.rstudio.com" )
# if ( !require( doParallel           )  ) install.packages( "doParallel"                  , repos = "http://cran.rstudio.com" )
# if ( !require( randomForest         )  ) install.packages( "randomForest"                , repos = "http://cran.rstudio.com" )
# if ( !require( parallelRandomForest )  ) install_bitbucket( "mkuhn/parallelRandomForest" , ref = "parallelRandomForest"      )
# if ( !require( ModelGood            )  ) install.packages( "ModelGood"                   , repos = "http://cran.rstudio.com" )
# if ( !require( neuralnet            )  ) install.packages( "neuralnet"                   , repos = "http://cran.rstudio.com" )
# if ( !require( tree                 )  ) install.packages( "tree"                        , repos = "http://cran.rstudio.com" )
# if ( !require( rpart                )  ) install.packages( "rpart"                       , repos = "http://cran.rstudio.com" )
# if ( !require( rpart.plot           )  ) install.packages( "rpart.plot"                  , repos = "http://cran.rstudio.com" )
# if ( !require( rattle               )  ) install.packages( "rattle"                      , repos = "http://cran.rstudio.com" )
# if ( !require( DAAG                 )  ) install.packages( "DAAG"                        , repos = "http://cran.rstudio.com" )
  if ( !require( knitr                )  ) install.packages( "knitr"                       , repos = "http://cran.rstudio.com" )
  if ( !require( fBasics              )  ) install.packages( "fBasics"                     , repos = "http://cran.rstudio.com" )
# if ( !require( scatterplot3d        )  ) install.packages( "scatterplot3d"               , repos = "http://cran.rstudio.com" )
# if ( !require( caret                )  ) install.packages( "caret"                       , repos = "http://cran.rstudio.com" , dependencies = c("Depends", "Suggests") )
# if ( !require( ResourceSelection    )  ) install.packages( "ResourceSelection"           , repos = "http://cran.rstudio.com" )
# if ( !require( smbinning            )  ) install.packages( "smbinning"                   , repos = "http://cran.rstudio.com" )
  if ( !require( RPostgreSQL          )  ) install.packages( "RPostgreSQL"                 , repos = "http://cran.rstudio.com" )
  if ( !require( readr                )  ) install.packages( "readr"                       , repos = "http://cran.rstudio.com" )
# if ( !require( ROCR                 )  ) install.packages( "ROCR"                        , repos = "http://cran.rstudio.com" )
# if ( !require( pROC                 )  ) install.packages( "pROC"                        , repos = "http://cran.rstudio.com" )
# if ( !require( e1071                )  ) install.packages( "e1071"                       , repos = "http://cran.rstudio.com" )
# if ( !require( Hmisc                )  ) install.packages( "Hmisc"                       , repos = "http://cran.rstudio.com" )
# if ( !require( nnet                 )  ) install.packages( "nnet"                        , repos = "http://cran.rstudio.com" )
# if ( !require( Zelig                )  ) install.packages( "Zelig"                       , repos = "http://cran.rstudio.com" )
  if ( !require( scales               )  ) install.packages( "scales"                      , repos = "http://cran.rstudio.com" )
  if ( !require( Cairo                )  ) install.packages( "Cairo"                       , repos = "http://cran.rstudio.com" )
  if ( !require( png                  )  ) install.packages( "png"                         , repos = "http://cran.rstudio.com" )
  if ( !require( RColorBrewer         )  ) install.packages( "RColorBrewer"                , repos = "http://cran.rstudio.com" )
  if ( !require( anytime              )  ) install.packages( "anytime"                     , repos = "http://cran.rstudio.com" )
  if ( !require( lattice              )  ) install.packages( "lattice"                     , repos = "http://cran.rstudio.com" )
        library( ggplot2              )
        library( gridExtra            )
        library( tidyr                )
        library( plyr                 )
#       library( smbinning            )
#       library( ggord                )
#       library( car                  )
#       library( fBasics              )
#       library( knitr                )
#       library( MASS                 )
#       library( ResourceSelection    )
#       library( pROC                 )
#       library( ROCR                 )
#       library( knitr                )
#       library( readr                )
#       library( mclust               )
#       library( class                )
#       library( knitr                )
#       library( fBasics              )
#       library( BCA                  )
#       library( ROCR                 )
# import the function from Github
# source_url('https://gist.github.com/fawda123/7471137/raw/cd6e6a0b0bdb4e065c597e52165e5ac887f5fe95/nnet_plot_update.r')
  sessionInfo(                        )
